{% set data = load_setup_py_data() %}
{% set version = environ.get("GIT_DESCRIBE_TAG").lstrip("v") %}

package:
  name: openmdao-bridge-matlab
  version: "{{ version }}"

about:
  home: https://github.com/ovidner/openmdao-bridge-matlab
  license: MIT
  license_file: LICENSE.txt

source:
  git_url: ../

build:
  noarch: python
  script: "python -m pip install . --no-deps --ignore-installed -vv "
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - pip
    - setuptools_scm
  run:
    - numpy
    - openmdao
    - python
    - pymatbridge

test:
  imports:
    - openmdao_bridge_matlab
